packages/astro-blog-loader/index.ts
packages/astro-blog-loader/package.json
packages/astro-blog-loader/src/loader.ts
packages/astro-blog-loader/tsconfig.json
yarn.lock

This PR migrates the `astro-blog-loader` package from headless-templates repo:
https://github.com/wix-incubator/headless-templates/tree/main/packages/astro-blog-loader

Migrate @wix/astro-blog-loader

---

packages/@wix-astro/src/integration.ts

Pull local env

---

.github/workflows/wixstro-react-sanity.yaml
examples/wixstro-react-demo/playwright.config.js
examples/wixstro-react-demo/wix.config.json

Note that it uses an api key generated by my account while my account was added as a site co-owner in the "Wixstro Examples" enterprise business.

test(wixstro-react-demo): update sanity flow to deploy on wix-sites.dev

---

packages/@wix-astro/src/components/login.astro

Hot fix.
we need to implement: `await getAuth().syncToWixPages({ force: true });`

Sync session with wix on login

---

packages/headless-components/stores/src/react/BuyNow.tsx
packages/headless-components/stores/src/server-actions/custom-checkout-action.ts
packages/headless-components/stores/src/services/buy-now-service.ts

* Add currency to custom checkout
* Add InStock and PreOrder avail. to BuyNow

Align components

---

packages/headless-components/ecom/src/services/current-cart-service.ts
packages/headless-components/stores/src/react/ProductActions.tsx

Part of:
https://github.com/wix-incubator/kitchensink/pull/80
Allow registering to added to cart event

Add registration to added cart event

---

packages/headless-components/bookings/react/package.json
packages/headless-components/ecom/package.json
packages/headless-components/ecom/react/package.json
packages/headless-components/ecom/services/package.json
packages/headless-components/media/package.json
packages/headless-components/media/react/package.json
packages/headless-components/media/services/package.json
packages/headless-components/stores/astro/actions/package.json
packages/headless-components/stores/package.json
packages/headless-components/stores/react/package.json
packages/headless-components/stores/server-actions/package.json
packages/headless-components/stores/services/package.json

adding the missing package.json files

---

examples/astro-stores-demo/src/components/store/ProductDetails.tsx
examples/astro-stores-demo/src/components/store/ProductList.tsx
examples/astro-stores-demo/src/layouts/StoreLayout.tsx
packages/headless-components/ecom/src/react/CurrentCart.tsx
packages/headless-components/media/src/react/FileUpload.tsx
packages/headless-components/stores/src/react/Product.tsx
packages/headless-components/stores/src/react/ProductVariantSelector.tsx
packages/headless-components/stores/src/react/ProductsList.tsx
packages/headless-components/stores/src/react/RelatedProducts.tsx
packages/headless-components/stores/src/react/SelectedVariant.tsx
packages/headless-components/stores/src/services/product-service.ts

This PR implements the missing "Root" concept across headless components and fixes TypeScript compatibility issues in JSDoc examples. All headless components now follow consistent patterns with proper service initialization and context management.

adding more root components

---

packages/headless-components/stores/src/react/SelectedVariant.tsx

we should have only one cart instance

---

examples/astro-stores-demo/src/components/store/CategoryPage.tsx
examples/astro-stores-demo/src/components/store/ProductDetails.tsx
packages/headless-components/stores/package.json
packages/headless-components/stores/src/services/selected-variant-service.ts

1. Change the `tsx` files so that `MediaGallery.Root` will always wrap `SelectedVariant.Root` since `selected-variant-service` needs `media-service`
2. Fixing the `media-service` media to display logic

fixing selected variants image + making the media service deps option 

---

examples/astro-stores-demo/src/components/store/CategoryPage.tsx
examples/astro-stores-demo/src/components/store/ProductActionButtons.tsx
examples/astro-stores-demo/src/components/store/ProductDetails.tsx
packages/headless-components/ecom/package.json
packages/headless-components/ecom/src/react/Commerce.tsx
packages/headless-components/ecom/src/react/index.tsx
packages/headless-components/stores/package.json
packages/headless-components/stores/src/react/ProductList.tsx
packages/headless-components/stores/src/react/core/SelectedVariant.tsx
packages/headless-components/stores/src/react/index.ts
packages/headless-components/utils/package.json
yarn.lock

`core` folder shouldnt be exported

remove core exports

---

examples/astro-blog-demo/src/react-pages/blog/[slug].tsx
examples/astro-blog-demo/src/styles/global-loader.css
packages/headless-components/blog/src/react/BlogPost.tsx
packages/headless-components/blog/src/react/styles.css

- Added `customStyles` allow consumers to control styles of various elements
- Added a whitelist of Blog-supported plugins in RicosViewer

[blog] Add theming properties for RicosViewer

---

packages/headless-components/media/package.json
packages/headless-components/media/src/react/WixMediaImage.tsx
yarn.lock

add support in shapes image in headless component

feat(shapes)

---

packages/headless-components/cms/src/react/CmsCollection.tsx
packages/headless-components/cms/src/react/core/CmsCollection.tsx
packages/headless-components/cms/src/react/core/index.tsx
packages/headless-components/cms/src/react/index.tsx
packages/headless-components/cms/src/services/cms-collection-service.ts
packages/headless-components/cms/src/services/index.ts

* integrated minimal working code for the client services, core component and headless component for the Root  collection with items

create initial root collection

---

packages/headless-components/restaurants-menus/package.json
packages/headless-components/restaurants-menus/src/react/Menu.tsx

chore(restaurants-menus): menu sections repeater

---

packages/headless-components/cms/package.json
packages/headless-components/cms/src/react/CmsItem.tsx
packages/headless-components/cms/src/react/core/CmsItem.tsx
packages/headless-components/cms/src/services/cms-item-service.ts
packages/headless-components/cms/src/services/index.ts
yarn.lock

Introduces CMS Item service and headless components for rendering individual CMS collection items with a unified field API.
- Reactive state management for individual CMS items
- Auto-loading from Wix Data API
- Server-side data loading support
**`CmsItem.Root`** - Service context provider
```tsx
<CmsItem.Root item={{ collectionId: 'MyCollection', id: 'item-123' }}>
{/* child components */}
</CmsItem.Root>
```
**`CmsItem.Field`** - Unified field component (replaces separate TextField, ImageField, etc.)
```tsx
// Text field
<CmsItem.Field fieldId="title" asChild>
{React.forwardRef(({ fieldValue, ...props }, ref) => (
<h1 ref={ref} {...props}>{fieldValue}</h1>
))}
</CmsItem.Field>
// Image field  
<CmsItem.Field fieldId="image" asChild>
{React.forwardRef(({ fieldValue, ...props }, ref) => ( …
```

[CMS] - Create Item service and CmsItem headless components

---

packages/headless-components/restaurants-menus/src/react/Item.tsx
packages/headless-components/restaurants-menus/src/react/Label.tsx
packages/headless-components/restaurants-menus/src/react/Menu.tsx
packages/headless-components/restaurants-menus/src/react/Menus.tsx
packages/headless-components/restaurants-menus/src/react/Modifier.tsx
packages/headless-components/restaurants-menus/src/react/ModifierGroup.tsx
packages/headless-components/restaurants-menus/src/react/Section.tsx
packages/headless-components/restaurants-menus/src/react/TestIds.ts
packages/headless-components/restaurants-menus/src/react/Variant.tsx
packages/headless-components/restaurants-menus/src/react/core/Item.tsx
packages/headless-components/restaurants-menus/src/react/core/Menus.tsx
packages/headless-components/restaurants-menus/src/react/core/index.ts
packages/headless-components/restaurants-menus/src/services/menus-service.ts
packages/headless-components/restaurants-menus/src/services/types.ts

Finish the first phase remains:
- manage panel
- locations
- multi menus
- html tag elements
- featured and outOfStock
- additional images

menus: finish

---

docs/api/FORM_INTERFACE.md
examples/astro-forms-demo/src/react-pages/index.tsx
packages/headless-components/forms/README.md
packages/headless-components/forms/package.json
packages/headless-components/forms/src/react/Form.tsx
packages/headless-components/forms/src/react/core/Form.tsx
packages/headless-components/forms/src/services/form-service.ts

- Improve API & types
- Add README
- Update docs
- Refactor to follow guidelines & improve consistency
- Move `Fields` service usage to core component

[forms] update stuff

---

packages/headless-components/blog/package.json
packages/headless-components/blog/src/services/blog-post-service.ts

[blog] Add a param to control whether to fetch sibling posts

---

packages/headless-components/ecom/package.json
packages/headless-components/stores/src/react/Product.test.tsx
packages/headless-components/stores/src/react/Product.tsx

this #pr fixes data-component-tag propogation

stores: fix data attribute for product.root

---

packages/headless-components/stores/package.json

bump stores -> 0.0.96

---

packages/headless-components/cms/src/react/CmsCollection.tsx
packages/headless-components/cms/src/react/core/CmsCollection.tsx

- Added `infiniteScroll` prop to `CmsCollection.Items` component
- Enhanced core Items render props with `loadNext()` function and `hasNext` boolean  
- Implemented IntersectionObserver for automatic pagination when scrolling near bottom
- Improved loading/error state handling to support progressive loading
- Added invisible sentinel element that triggers next page load when visible
- ✅ Automatic pagination on scroll with 100px trigger margin
- ✅ Graceful handling of loading states during pagination  
- ✅ Backward compatible (infinite scroll is opt-in)
- ✅ Proper cleanup of IntersectionObserver on unmount
```tsx
<CmsCollection.Items infiniteScroll>
<CmsCollection.ItemRepeater>
<CmsItem.Field fieldId="title" asChild>
{({ fieldValue }, ref) => <h2 ref={ref}>{fieldValue}</h2>} …
```

[CMS] - Implemented infinite scroll logic for Items
